name: Pre

inputs:
  GPG_PRIVATE_KEY:
    description: 'GPG Private key'
    required: true
  GPG_PASSPHRASE:
    description: 'GPG Passphrase'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        useradd -m builder
        rm -r /__t/*
        mount /dev/root /mnt
        cd /mnt
        rm -r bin lib* boot media srv sbin snap usr mnt root sys tmp

    - uses: actions/cache/restore@v4
      with:
        path: |
          /__w/auto-aur/auto-aur
          /var/cache/pacman/pkg
          /home/builder/.cache
        key: cache-${{ github.sha }}
        restore-keys: cache-

    - shell: bash
      run: |
        pacman --noconfirm -Syu
        pacman --noconfirm -S git
        git config --global --add safe.directory $PWD

    - uses: actions/checkout@v4

    - name: Setup (root)
      run: scripts/setup-root.sh
      shell: bash

    - name: Setup (builder)
      run: sudo -E -u builder bash ./scripts/setup-builder.sh
      shell: bash
      env:
        GPG_PASSPHRASE: ${{ inputs.GPG_PASSPHRASE }}
        GPG_PRIVATE_KEY: ${{ inputs.GPG_PRIVATE_KEY }}
