name: Post

inputs:
  FIREBASE_SERVICE_ACCOUNT:
    description: 'Service account JSON key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate UI
      shell: bash
      run: python scripts/genui.py

    - name: Git
      shell: bash
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Data"
          git push
        fi

    - uses: actions/cache/save@v4
      if: ${{ !cancelled() }}
      with:
        path: /var/cache/pacman/pkg
        key: pkgcache-${{ github.sha }}

    - uses: akku1139/auto-aur/.github/actions/deploy@main
      with:
        FIREBASE_SERVICE_ACCOUNT: ${{ inputs.FIREBASE_SERVICE_ACCOUNT }}
