name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - public/**

concurrency:
  group: deploy
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base
     options: --privileged

    steps:
      - uses: actions/checkout@v4

      - uses: akku1139/auto-aur/.github/actions/deploy@main
        with:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
