name: Deploy

on:
  workflow_dispatch:

concurrency:
  group: deploy

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged

    steps:
      - uses: actions/checkout@v6

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "public/"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5

      - run: echo "/__e/node20/bin" >> $GITHUB_PATH

      - uses: FirebaseExtended/action-hosting-deploy@v0.10.0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: auto-aur
          channelId: live
