name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - public/**

concurrency:
  group: deploy
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
