name: Deploy

on:
  workflow_dispatch:

concurrency:
  group: deploy

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged

    steps:
      - uses: actions/cache@v5
        with:
          path: | # Must be synchronized with save
            /__w/auto-aur/auto-aur
            /var/cache/pacman/pkg
            /home/builder/.cache
            /home/builder/.cargo
            /home/builder/go
            /home/builder/.dub
            /home/builder/.cabal
          # /home/builder/.ccache
          key: cache-${{ github.sha }}
          restore-keys: cache-

      - uses: actions/checkout@v6

      - name: Setup (root)
        run: scripts/setup-root.sh

      - name: Setup (builder)
        run: sudo -E -u builder bash ./scripts/setup-builder.sh
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Generate UI
        run: python scripts/genui.py

      - name: Git
        id: git
        if: ${{ !cancelled() }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "change=true" >> $GITHUB_OUTPUT
            git pull
            git add -A
            git commit -m "Data"
            git push
          else
            echo "There are no changes."
            echo "change=false" >> $GITHUB_OUTPUT
          fi
          git clean -ffdx
          git reset --hard HEAD

      - name: Upload Pages Artifact
        if: ${{ steps.git.outputs.change == 'true' }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: "public/"

      - name: Deploy to GitHub Pages
        if: ${{ steps.git.outputs.change == 'true' }}
        uses: actions/deploy-pages@v5

      - run: echo "/__e/node20/bin" >> $GITHUB_PATH
        if: ${{ steps.git.outputs.change == 'true' }}

      - uses: FirebaseExtended/action-hosting-deploy@v0.10.0
        if: ${{ steps.git.outputs.change == 'true' }}
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: auto-aur
          channelId: live
