name: Local Packages

on:
  workflow_dispatch:
  push:
    paths:
      - local/**

concurrency:
  group: local
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base
     options: --privileged

    steps:
      - uses: akku1139/auto-aur/.github/actions/pre@main
        with:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build local packages
        run: bash -ex scripts/localbuild.sh

      - uses: akku1139/auto-aur/.github/actions/post@main
