name: Local Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - local/**

concurrency:
  group: local
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base
     options: --privileged

    steps:
      - uses: akku1139/auto-aur/.github/workflows/setup.yml@main

      - name: Build local packages
        run: bash -ex scripts/localbuild.sh

      - uses: ./.github/workflows/post.yml
