name: Post

on:
  workflow_call:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base
     options: --privileged

    steps:
      - name: Generate UI
        run: python scripts/genui.py

      - name: Git
        run: |
          # if [ -n "$(git status ./public/ --porcelain)" ]; then
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Data"
            git push
          fi

      - uses: actions/cache/save@v4
        with:
          path: /var/cache/pacman/pkg
          key: pkgcache-${{ github.sha }}

      - uses: ./.github/workflows/deploy.yml
