name: Repo

on:
  push:
    paths-ignore:
      - repo/**
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base
     options: --privileged

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache-packages
        with:
          path: /var/cache/pacman/pkg
          key: pkgcache

      - name: Build
        run: scripts/build.sh

      - name: Git
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Data"
            git push
          fi
