name: Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '47 8 */10 * *'
  push:
    # branches:
    #   - main
    paths:
      - package.txt
      # - patches/**

concurrency:
  group: repo
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base
     options: --privileged

    steps:
      - uses: actions/cache/restore@v4
        with:
          path: /var/cache/pacman/pkg
          key: pkgcache-${{ github.sha }}
          restore-keys: pkgcache-

      - run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S git
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@v4

      - name: Setup (root)
        run: bash scripts/setup.sh

      - name: Setup (builder)
        run: sudo -u builder bash ./scripts/setup-builder.sh
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY:  ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build AUR
        run: bash -ex scripts/build.sh

      - uses: ./.github/workflows/post.yml
