name: Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '47 8 */10 * *'
  push:
    paths-ignore:
      - repo/**
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base
     options: --privileged

    steps:
      - run: |
          whoami
          echo ${HOME}

      - uses: akku1139/ghaction-import-gpg@master
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: "2ECF4E27AAACF8F478631D73AA4D941DB6C633AF"

      - uses: actions/cache@v4
        with:
          save-always: true
          path: /var/cache/pacman/pkg
          key: pkgcache-${{ github.sha }}
          restore-keys: pkgcache-

      - run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S git
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@v4

      - name: Setup
        run: bash scripts/setup.sh
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build
        run: bash scripts/build.sh

      - name: Git
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Data"
            git push
          fi

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./repo/"

  deploy:
    needs: main
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
