name: Repo

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Cache Packages
      #   id: cache-packages
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       bin
      #       boot
      #       dev
      #       etc
      #       fat
      #       home
      #       lib
      #       lib64
      #       lost+found
      #       mnt
      #       opt
      #       proc
      #       root
      #       run
      #       sbin
      #       srv
      #       sys
      #       tmp
      #       usr
      #       var
      #     key: packages-${{ hashFiles('/tmp/packages') }}

      - name: Setup ArchLinux
        # if: steps.cache-packages.outputs.cache-hit != 'true'
        run: bash ./scripts/setup.sh

      - name: Build
        run: "sudo ./bin/arch-chroot ./ bash /scripts/build.sh"

      - name: Git
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then
            git add .
            git commit -m "build"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
