name: Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '47 8 */10 * *'
  push:
    # branches:
    #   - main
    paths:
      - packages.txt
      # - patches/**

concurrency:
  group: repo
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged

    steps:
      - shell: bash
        run: |
          useradd -m builder
          rm -r /__t/*
          mount /dev/root /mnt
          chroot /mnt bash
          df -h
          echo "**** tidy up ****"
          # https://github.com/NobuoTsukamoto/my_actions_test/blob/main/.github/workflows/test_contains.yml
          rm -rf /home/work/* /var/* /opt/* /usr/local /usr || true
          rm -rf "/usr/share/dotnet" || true
          rm -rf "$AGENT_TOOLSDIRECTORY" || true
          rm -rf "/usr/lib/jvm" || true
          rm -rf "/usr/share/swift" || true
          rm -rf "/usr/share/kotlinc" || true
          rm -rf "/usr/share/miniconda" || true
          rm -rf "/usr/share/sbt" || true
          rm -rf "/usr/bin/yq" || true
          rm -rf "/home/.dotnet/tools" || true
          rm -rf "/etc/skel/.dotnet/tools" || true
          rm -rf "/home/linuxbrew" || true
          rm -rf "/usr/share/apache-maven-3.8.8" || true
          rm -rf "/usr/share/gradle-8.7" || true
          rm -rf "/home/.nvm" || true
          rm -rf "/usr/bin/composer" || true
          rm -rf "/home/perflog" || true
          rm -rf "/usr/libexec/docker/cli-plugins" || true
          rm -rf "/usr/bin/docker-credential-ecr-login" || true
          df -h

      - uses: actions/cache/restore@v4
        with:
          path: |
            /__w/auto-aur/auto-aur
            /var/cache/pacman/pkg
            /home/builder/.cache
          key: cache-${{ github.sha }}
          restore-keys: cache-

      - shell: bash
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S git
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@v4

      - name: Setup (root)
        run: scripts/setup-root.sh
        shell: bash

      - name: Setup (builder)
        run: sudo -E -u builder bash ./scripts/setup-builder.sh
        shell: bash
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}


      - name: Build AUR
        run: sudo -u builder bash -ex scripts/build.sh

      # - uses: mxschmitt/action-tmate@v3
      #   if: ${{ failure() }}

      - name: Generate UI
        shell: bash
        run: python scripts/genui.py

      - name: Git
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Data"
            git push
          fi
          git clean -ffdx
          git reset --hard HEAD

      - uses: actions/cache/save@v4
        if: ${{ !cancelled() }}
        with:
          path: |
            /__w/auto-aur/auto-aur
            /var/cache/pacman/pkg
            /home/builder/.cache
          key: cache-${{ github.sha }}

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - run: echo "/__e/node20/bin" >> $GITHUB_PATH
        shell: bash

      - uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: auto-aur
          channelId: live
