name: Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '47 8 */10 * *'
  push:
    # branches:
    #   - main
    paths:
      - packages.txt
      # - patches/**

concurrency:
  group: repo
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: archlinux:base
     options: --privileged

    steps:
      - uses: akku1139/auto-aur/.github/actions/pre@main
        with:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build AUR
        run: bash -ex scripts/build.sh

      - uses: akku1139/auto-aur/.github/actions/post@main
