name: Repo

on:
  workflow_dispatch:
    inputs:
      tmate:
        type: boolean
        description: 'SSH debug'
        required: false
        default: false
      cmd:
        type: string
        description: 'Custom commands'
        required: false
        default: ''

  schedule:
    - cron: '47 8 * * *'
  push:
    # branches:
    #   - main
    paths:
      - packages.txt
      # - patches/**

concurrency:
  group: repo
  # cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged

    steps:
      - name: Add Builder user
        run: useradd -m builder

      - uses: actions/cache/restore@v4
        with:
          path: | # Must be synchronized with save
            /__w/auto-aur/auto-aur
            /var/cache/pacman/pkg
            /home/builder/.cache
            /home/builder/.cargo
            /home/builder/go
            /home/builder/.dub
            /home/builder/.cabal
          # /home/builder/.ccache
          key: cache-${{ github.sha }}
          restore-keys: cache-

      - name: Pre setup
        run: |
          set -x

          pacman --noconfirm -Syu
          pacman --noconfirm -S git btrfs-progs
          git config --global --add safe.directory $PWD

          # language support?
          rm -r /__t/*

          mount /dev/root /mnt
          curl -L https://github.com/akku1139/auto-aur/raw/refs/heads/main/scripts/tidyup.sh > /mnt/tidyup.sh
          chmod 777 /mnt/tidyup.sh
          chroot /mnt /tidyup.sh &

          mkdir /pre /ext

          if [ "/dev/sda1" = $( mount | grep -F "/__e" | cut -d " " -f1 ) ]; then
            mount /dev/sdb1 /pre
          else
            mount /dev/sda1 /pre
          fi

          # move swap 1
          swapoff /pre/swapfile
          rm -r /pre/*

          fallocate -l $( df -h | awk '$6 == "/pre" { print $4 }' ) /pre/fs
          mkfs.btrfs -f /pre/fs
          mount -o compress-force=zstd,nobarrier,noatime /pre/fs /ext

          df -h

          # builder setup
          mkdir /ext/builder
          chown builder:builder /ext/builder

          # move swap 2
          fallocate -l 8GB /swapfile
          chmod 0600 /swapfile
          mkswap /swapfile
          losetup -f /swapfile
          swapon $( losetup -a | grep -F "/swapfile" | cut -d: -f1 )

      - uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.tmate }}
        with:
          detached: true

      - uses: actions/checkout@v4

      - name: Setup (root)
        run: scripts/setup-root.sh

      - name: Setup (builder)
        run: sudo -E -u builder bash ./scripts/setup-builder.sh
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SCCACHE_CLIENT_TOKEN: ${{ secrets.SCCACHE_CLIENT_TOKEN }}
          SCCACHE_SCHEDULER_ADDR: ${{ secrets.SCCACHE_SCHEDULER_ADDR }}
          SCCACHE_SERVER_TOKEN: ${{ secrets.SCCACHE_SERVER_TOKEN }}
          TCPEXPOSER_PRIVATE_KEY: ${{ secrets.TCPEXPOSER_PRIVATE_KEY }}
          TCPEXPOSER_PUBLIC_KEY: ${{ secrets.TCPEXPOSER_PUBLIC_KEY }}

      - name: Custom commands
        if: ${{ inputs.cmd != '' }}
        run: ${{ inputs.cmd }}

      - name: Build AUR
        run: sudo -u builder bash -ex scripts/build.sh

      - name: Generate UI
        run: python scripts/genui.py

      - name: Git
        id: git
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "change=true" >> $GITHUB_OUTPUT
            git pull
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Data"
            git push
          else
            echo "change=false" >> $GITHUB_OUTPUT
          fi
          git clean -ffdx
          git reset --hard HEAD

      - uses: actions/cache/save@v4
        if: ${{ !cancelled() }}
        with:
          path: |
            /__w/auto-aur/auto-aur
            /var/cache/pacman/pkg
            /home/builder/.cache
            /home/builder/.cargo
            /home/builder/go
            /home/builder/.dub
            /home/builder/.cabal
          # /home/builder/.ccache
          key: cache-${{ github.sha }}

      - name: Upload Pages Artifact
        if: ${{ steps.git.outputs.change }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

      - name: Deploy to GitHub Pages
        if: ${{ steps.git.outputs.change }}
        uses: actions/deploy-pages@v4

      - run: echo "/__e/node20/bin" >> $GITHUB_PATH
        if: ${{ steps.git.outputs.change }}

      - uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        if: ${{ steps.git.outputs.change }}
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: auto-aur
          channelId: live

      # - uses: mxschmitt/action-tmate@v3
      #   if: ${{ ( failure() ) && ! ( github.event_name == 'workflow_dispatch' && inputs.tmate ) }}

      - name: Debug info
        if: ${{ failure() }}
        run: |
          df -h

  dist:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged

    steps:
      - name: Install deps
        run: pacman --noconfirm -Syu sccache bubblewrap openssh

      - name: SSH config
        run: |
          cat > /root/.ssh/id_tcpexposer.com.pub << EOL
          ${{ secrets.TCPEXPOSER_PUBLIC_KEY }}
          EOL
          
          cat > /root/.ssh/id_tcpexposer.com << EOL
          ${{ secrets.TCPEXPOSER_PRIVATE_KEY }}
          EOL
          
          cat >> /root/.ssh/config << EOL
          Host tcpexposer.com
            User aku-2
            HostName tcpexposer.com
            TCPKeepAlive yes
            IdentityFile ~/.ssh/id_tcpexposer.com
            IdentitiesOnly yes
          EOL
          
          cat >> /root/.ssh/known_hosts << EOL
          # tcpexposer.com:22 SSH-2.0-sish
          |1|PWKuAKfpfTyXmLUOlXZX2W+7C8Y=|pdbC3oKKs4H7lSgFHODZGyj1JuU= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF9qb8hhyV/kBYq/X00tsnsbKdT5bXli5MN2frvtHqdw
          # tcpexposer.com:22 SSH-2.0-sish
          |1|GQBsQinK5IywjROSdpa1Lliczi0=|pRvgj+90jrTLEiqUvoSoL2syr9A= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCeuHC9irjuXnBGa6ZxHYAgu93rrzLYT37RxTubXo9HInJwfqZZ5z2OJFgVt3hc5tTr1Nt6ozkDMrG/p1U2teAX+aRUZ0CyEbUGofChU8n9ZEDv3S+VIIUMfAXn966nIUVjai2gmcRnENl8i0KZ5YRjS5UTmvz15N4RfhA8p0vltHwTOo4z86aRHuHI5M1f5g2GX4TU2zp+BR0T6qJiSGFLHqZsNgZ1NVwwyNOFY5IbkqxywmLwwU4jQXhoiVpJsI+ylzWdvS4EhXjbAlYSb13yajiXYNNlEVLb+IPyAvjsIUXe7cPvjrWMW8ZSvHUehCRPKz/BApQJSbF9Dqq72B+e8WRf1TGN2tDKh7ew/eBVmQtGfjPsytulPH5RnhFw6gpIla0r+sV/rLRmsYpRG4/T22LvbDVRd88C2kgnF18MlErKH1k0jSOZ87vVYASQ4Rbr8WAY/AHMwpZErX7Ql5g+4Hg0YDM8Y/TqT1h8y/VocanBAgOHfUr5O9SnCX9CmuE=
          # tcpexposer.com:22 SSH-2.0-sish
          # tcpexposer.com:22 SSH-2.0-sish
          # tcpexposer.com:22 SSH-2.0-sish
          EOL

      - name: Start sccache
        run: |
          cat > /sccache-server.conf << EOL
          # This is where client toolchains will be stored.
          cache_dir = "/tmp/toolchains"
          # The maximum size of the toolchain cache, in bytes.
          # If unspecified the default is 10GB.
          # toolchain_cache_size = 10737418240
          # A public IP address and port that clients will use to connect to this builder.
          public_addr = "${{ secrets.SCCACHE_SERVER_ADDR }}.tcpexposer.com:443"
          # The URL used to connect to the scheduler (should use https, given an ideal
          # setup of a HTTPS server in front of the scheduler)
          scheduler_url = "https://${{ secrets.SCCACHE_SCHEDULER_ADDR }}.tcpexposer.com"

          [builder]
          type = "overlay"
          # The directory under which a sandboxed filesystem will be created for builds.
          build_dir = "/tmp/build"
          # The path to the bubblewrap version 0.3.0+ `bwrap` binary.
          bwrap_path = "/usr/bin/bwrap"

          [scheduler_auth]
          type = "token"
          token = "${{ secrets.SCCACHE_SERVER_TOKEN }}"
          EOL

          sccache-dist server --config /sccache-server.conf &
          ssh at3o07rszaubbafwd6oni2ch4e:80:localhost:443 aku-2@tcpexposer.com &

      - name: Wait main
        run: |
          sleep 1500
