name: SSH

on:
  workflow_dispatch:
    inputs:
      port:
        description: SSH port
        required: false
        default: "22"
        type: string

# permissions:
#   contents: write
#   pages: write
#   id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged

    steps:
      - uses: mxschmitt/action-tmate@v3
        with:
          tmate-server-port: ${{ inputs.port }}
